var COMPILED=!0,goog=goog||{};goog.global=this;goog.DEBUG=!0;goog.LOCALE='en';goog.TRUSTED_SITE=!0;goog.provide=function(a){if(!COMPILED){if(goog.isProvided_(a))throw Error('Namespace "'+a+'" already declared.');delete goog.implicitNamespaces_[a];for(var b=a;(b=b.substring(0,b.lastIndexOf('.')))&&!goog.getObjectByName(b);)goog.implicitNamespaces_[b]=!0}goog.exportPath_(a)};
goog.setTestOnly=function(a){if(COMPILED&&!goog.DEBUG)throw a=a||'',Error('Importing test-only code into non-debug environment'+a?': '+a:'.');};COMPILED||(goog.isProvided_=function(a){return!goog.implicitNamespaces_[a]&&!!goog.getObjectByName(a)},goog.implicitNamespaces_={});goog.exportPath_=function(a,b,c){a=a.split('.');c=c||goog.global;a[0]in c||!c.execScript||c.execScript('var '+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&goog.isDef(b)?c[d]=b:c=c[d]?c[d]:c[d]={}};
goog.getObjectByName=function(a,b){for(var c=a.split('.'),d=b||goog.global,e;e=c.shift();)if(goog.isDefAndNotNull(d[e]))d=d[e];else return null;return d};goog.globalize=function(a,b){var c=b||goog.global,d;for(d in a)c[d]=a[d]};
goog.addDependency=function(a,b,c){if(!COMPILED){var d;a=a.replace(/\\/g,'/');for(var e=goog.dependencies_,g=0;d=b[g];g++)e.nameToPath[d]=a,a in e.pathToNames||(e.pathToNames[a]={}),e.pathToNames[a][d]=!0;for(d=0;b=c[d];d++)a in e.requires||(e.requires[a]={}),e.requires[a][b]=!0}};goog.ENABLE_DEBUG_LOADER=!0;
goog.require=function(a){if(!COMPILED&&!goog.isProvided_(a)){if(goog.ENABLE_DEBUG_LOADER){var b=goog.getPathFromDeps_(a);if(b){goog.included_[b]=!0;goog.writeScripts_();return}}a='goog.require could not find: '+a;goog.global.console&&goog.global.console.error(a);throw Error(a);}};goog.basePath='';goog.nullFunction=function(){};goog.identityFunction=function(a,b){return a};goog.abstractMethod=function(){throw Error('unimplemented abstract method');};
goog.addSingletonGetter=function(a){a.getInstance=function(){if(a.instance_)return a.instance_;goog.DEBUG&&(goog.instantiatedSingletons_[goog.instantiatedSingletons_.length]=a);return a.instance_=new a}};goog.instantiatedSingletons_=[];
!COMPILED&&goog.ENABLE_DEBUG_LOADER&&(goog.included_={},goog.dependencies_={pathToNames:{},nameToPath:{},requires:{},visited:{},written:{}},goog.inHtmlDocument_=function(){var a=goog.global.document;return'undefined'!=typeof a&&'write'in a},goog.findBasePath_=function(){if(goog.global.CLOSURE_BASE_PATH)goog.basePath=goog.global.CLOSURE_BASE_PATH;else if(goog.inHtmlDocument_())for(var a=goog.global.document.getElementsByTagName('script'),b=a.length-1;0<=b;--b){var c=a[b].src,d=c.lastIndexOf('?'),d=
-1==d?c.length:d;if('base.js'==c.substr(d-7,7)){goog.basePath=c.substr(0,d-7);break}}},goog.importScript_=function(a){var b=goog.global.CLOSURE_IMPORT_SCRIPT||goog.writeScriptTag_;!goog.dependencies_.written[a]&&b(a)&&(goog.dependencies_.written[a]=!0)},goog.writeScriptTag_=function(a){if(goog.inHtmlDocument_()){var b=goog.global.document;if('complete'==b.readyState){if(/\bdeps.js$/.test(a))return!1;throw Error('Cannot write "'+a+'" after document load');}b.write('<script type="text/javascript" src="'+
a+'">\x3c/script>');return!0}return!1},goog.writeScripts_=function(){function a(e){if(!(e in d.written)){if(!(e in d.visited)&&(d.visited[e]=!0,e in d.requires))for(var f in d.requires[e])if(!goog.isProvided_(f))if(f in d.nameToPath)a(d.nameToPath[f]);else throw Error('Undefined nameToPath for '+f);e in c||(c[e]=!0,b.push(e))}}var b=[],c={},d=goog.dependencies_,e;for(e in goog.included_)d.written[e]||a(e);for(e=0;e<b.length;e++)if(b[e])goog.importScript_(goog.basePath+b[e]);else throw Error('Undefined script input');
},goog.getPathFromDeps_=function(a){return a in goog.dependencies_.nameToPath?goog.dependencies_.nameToPath[a]:null},goog.findBasePath_(),goog.global.CLOSURE_NO_DEPS||goog.importScript_(goog.basePath+'deps.js'));
goog.typeOf=function(a){var b=typeof a;if('object'==b)if(a){if(a instanceof Array)return'array';if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if('[object Window]'==c)return'object';if('[object Array]'==c||'number'==typeof a.length&&'undefined'!=typeof a.splice&&'undefined'!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable('splice'))return'array';if('[object Function]'==c||'undefined'!=typeof a.call&&'undefined'!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable('call'))return'function'}else return'null';
else if('function'==b&&'undefined'==typeof a.call)return'object';return b};goog.isDef=function(a){return void 0!==a};goog.isNull=function(a){return null===a};goog.isDefAndNotNull=function(a){return null!=a};goog.isArray=function(a){return'array'==goog.typeOf(a)};goog.isArrayLike=function(a){var b=goog.typeOf(a);return'array'==b||'object'==b&&'number'==typeof a.length};goog.isDateLike=function(a){return goog.isObject(a)&&'function'==typeof a.getFullYear};goog.isString=function(a){return'string'==typeof a};
goog.isBoolean=function(a){return'boolean'==typeof a};goog.isNumber=function(a){return'number'==typeof a};goog.isFunction=function(a){return'function'==goog.typeOf(a)};goog.isObject=function(a){var b=typeof a;return'object'==b&&null!=a||'function'==b};goog.getUid=function(a){return a[goog.UID_PROPERTY_]||(a[goog.UID_PROPERTY_]=++goog.uidCounter_)};goog.removeUid=function(a){'removeAttribute'in a&&a.removeAttribute(goog.UID_PROPERTY_);try{delete a[goog.UID_PROPERTY_]}catch(b){}};
goog.UID_PROPERTY_='closure_uid_'+(1E9*Math.random()>>>0);goog.uidCounter_=0;goog.getHashCode=goog.getUid;goog.removeHashCode=goog.removeUid;goog.cloneObject=function(a){var b=goog.typeOf(a);if('object'==b||'array'==b){if(a.clone)return a.clone();var b='array'==b?[]:{},c;for(c in a)b[c]=goog.cloneObject(a[c]);return b}return a};goog.bindNative_=function(a,b,c){return a.call.apply(a.bind,arguments)};
goog.bindJs_=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};goog.bind=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf('native code')?goog.bind=goog.bindNative_:goog.bind=goog.bindJs_;return goog.bind.apply(null,arguments)};
goog.partial=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=Array.prototype.slice.call(arguments);b.unshift.apply(b,c);return a.apply(this,b)}};goog.mixin=function(a,b){for(var c in b)a[c]=b[c]};goog.now=goog.TRUSTED_SITE&&Date.now||function(){return+new Date};
goog.globalEval=function(a){if(goog.global.execScript)goog.global.execScript(a,'JavaScript');else if(goog.global.eval)if(null==goog.evalWorksForGlobals_&&(goog.global.eval('var _et_ = 1;'),'undefined'!=typeof goog.global._et_?(delete goog.global._et_,goog.evalWorksForGlobals_=!0):goog.evalWorksForGlobals_=!1),goog.evalWorksForGlobals_)goog.global.eval(a);else{var b=goog.global.document,c=b.createElement('script');c.type='text/javascript';c.defer=!1;c.appendChild(b.createTextNode(a));b.body.appendChild(c);
b.body.removeChild(c)}else throw Error('goog.globalEval not available');};goog.evalWorksForGlobals_=null;goog.getCssName=function(a,b){var c=function(a){return goog.cssNameMapping_[a]||a},d=function(a){a=a.split('-');for(var b=[],d=0;d<a.length;d++)b.push(c(a[d]));return b.join('-')},d=goog.cssNameMapping_?'BY_WHOLE'==goog.cssNameMappingStyle_?c:d:function(a){return a};return b?a+'-'+d(b):d(a)};goog.setCssNameMapping=function(a,b){goog.cssNameMapping_=a;goog.cssNameMappingStyle_=b};
!COMPILED&&goog.global.CLOSURE_CSS_NAME_MAPPING&&(goog.cssNameMapping_=goog.global.CLOSURE_CSS_NAME_MAPPING);goog.getMsg=function(a,b){var c=b||{},d;for(d in c){var e=(''+c[d]).replace(/\$/g,'$$$$');a=a.replace(RegExp('\\{\\$'+d+'\\}','gi'),e)}return a};goog.getMsgWithFallback=function(a,b){return a};goog.exportSymbol=function(a,b,c){goog.exportPath_(a,b,c)};goog.exportProperty=function(a,b,c){a[b]=c};
goog.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a};
goog.base=function(a,b,c){var d=arguments.callee.caller;if(d.superClass_)return d.superClass_.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var e=Array.prototype.slice.call(arguments,2),g=!1,f=a.constructor;f;f=f.superClass_&&f.superClass_.constructor)if(f.prototype[b]===d)g=!0;else if(g)return f.prototype[b].apply(a,e);if(a[b]===d)return a.constructor.prototype[b].apply(a,e);throw Error('goog.base called from a method of one name to a method of a different name');};
goog.scope=function(a){a.call(goog.global)};var tripbuddy={core:{}};tripbuddy.core.util={};
tripbuddy.core.util.HttpPostFix=function(a){a.defaults.headers.post['Content-Type']='application/x-www-form-urlencoded;charset=utf-8';a.defaults.transformRequest=[function(a){if(angular.isObject(a)&&'[object File]'!==String(a)){var c='',d,e,g,f,l,h,k;for(d in a)if(e=a[d],e instanceof Array)for(k=0;k<e.length;++k)l=e[k],g=d+'['+k+']',h={},h[g]=l,c+=param(h)+'&';else if(e instanceof Object)for(f in e)l=e[f],g=d+'['+f+']',h={},h[g]=l,c+=param(h)+'&';else void 0!==e&&null!==e&&(c+=encodeURIComponent(d)+
'='+encodeURIComponent(e)+'&');a=c.length?c.substr(0,c.length-1):c}return a}]};tripbuddy.core.util.HttpPostFix.$inject=['$httpProvider'];tripbuddy.core.page={};tripbuddy.core.page.PageStateService=function(){this.title='UNSET';this.activePage='events'};tripbuddy.components={};tripbuddy.components.event={};MPG=24;DAYS=[{'long':'sunday','short':'sun'},{'long':'monday','short':'mon'},{'long':'tuesday','short':'tue'},{'long':'wednesday','short':'wed'},{'long':'thursday','short':'thu'},{'long':'friday','short':'fri'},{'long':'saturday','short':'sat'}];
MONTHS=[{'long':'january','short':'jan'},{'long':'february','short':'feb'},{'long':'march','short':'mar'},{'long':'april','short':'apr'},{'long':'may','short':'may'},{'long':'june','short':'jun'},{'long':'july','short':'jul'},{'long':'august','short':'aug'},{'long':'september','short':'sep'},{'long':'october','short':'oct'},{'long':'november','short':'nov'},{'long':'december','short':'dec'}];
tripbuddy.components.event.EventListDirective=function(a,b){return{restrict:'E',templateUrl:'/components/event/list/event-list-directive.html',link:function(a,d,e){a.prices={gas:4.5};a.days=DAYS;a.months=MONTHS;a.prices.mile=a.prices.gas/MPG;a.events=[];a.getCost=function(b){switch(b.event_type){case 'hotel':return b.nightly_price*b.nights;case 'driving':return b.distance*a.prices.mile}};a.getTotalCost=function(){var b=0;angular.forEach(a.events,function(d){b+=a.getCost(d)});return b};a.refresh=function(){b.list().then(function(b){a.events=
b})};a.refresh()}}};tripbuddy.components.event.EventListDirective.$inject=['pageState','eventData'];tripbuddy.components.location={};tripbuddy.components.location.list={};
tripbuddy.components.location.list.LocationListViewCtrl=function(a,b,c){a.data=c.locations;a.oldLocation=null;a.gridOptions=c.gridOptions;a.refresh=function(){c.list()};a.open=function(){console.log('open');a.gridOptions.selectedItems&&1==a.gridOptions.selectedItems.length?console.log(a.gridOptions.selectedItems[0]):(console.log('failed: Need one selectedItem.'),console.log(a.gridOptions),console.log(a.data))};a.openMap=function(){console.log('openMap');if(a.gridOptions.selectedItems&&1==a.gridOptions.selectedItems.length){var b=
a.gridOptions.selectedItems[0];b.geopt&&(url='https://maps.google.com?q='+b.geopt.lat+','+b.geopt.lon,window.open(url,'_blank'))}else console.log('failed: Need one selectedItem.'),console.log(a.gridOptions),console.log(a.data)};a.create=function(){console.log('create');c.save({name:'Untitled location'})};a.delete=function(){window.confirm('Are you sure you want to delete this location?  This action cannot be undone.')&&c.delete(a.gridOptions.selectedItems[0])};a.$on('ngGridEventStartCellEdit',function(b){a.oldLocation=
angular.copy(b.targetScope.row.entity)});a.$on('ngGridEventEndCellEdit',function(b){b=b.targetScope.row.entity;angular.equals(a.oldLocation,b)||c.save(b)});a.refresh()};tripbuddy.components.location.list.LocationListViewCtrl.$inject=['$scope','$state','locationData'];tripbuddy.components.PageSectionStates=function(a,b){a.state('events',{url:'/events',views:{'page.leftwell':{templateUrl:'/components/event/list/views/leftwell.html'},'page.content':{templateUrl:'/components/event/list/views/content.html'},'page.rightwell':{templateUrl:'/components/event/list/views/rightwell.html'},'page.footer':{templateUrl:'/components/event/list/views/footer.html'},'page.toolbar':{templateUrl:'/components/event/list/views/toolbar.html'}}}).state('event',{url:'/event/:eventId',
views:{'page.leftwell':{templateUrl:'/components/event/detail/views/leftwell.html'},'page.content':{templateUrl:'/components/event/detail/views/content.html'},'page.rightwell':{templateUrl:'/components/event/detail/views/rightwell.html'},'page.footer':{templateUrl:'/components/event/detail/views/footer.html'},'page.toolbar':{templateUrl:'/components/event/detail/views/toolbar.html'}}}).state('locations',{url:'/locations',views:{'page.leftwell':{templateUrl:'/components/location/list/views/leftwell.html'},
'page.toolbar':{templateUrl:'/components/location/list/views/toolbar.html',controller:'locationListViewCtrl'},'page.content':{templateUrl:'/components/location/list/views/content.html',controller:'locationListViewCtrl'},'page.rightwell':{templateUrl:'/components/location/list/views/rightwell.html'},'page.footer':{templateUrl:'/components/location/list/views/footer.html'}}}).state('location',{url:'/location/:locationId',views:{'page.leftwell':{templateUrl:'/components/location/detail/views/leftwell.html'},
'page.content':{templateUrl:'/components/location/detail/views/content.html'},'page.rightwell':{templateUrl:'/components/location/detail/views/rightwell.html'},'page.footer':{templateUrl:'/components/location/detail/views/footer.html'},'page.toolbar':{templateUrl:'/components/location/detail/views/toolbar.html'}}});b.html5Mode(!0)};tripbuddy.components.PageSectionStates.$inject=['$stateProvider','$locationProvider'];tripbuddy.core.page.PageDirective=function(a,b){return{restrict:'E',templateUrl:'/core/page/page-directive.html',link:function(c){c.pageState=a;c.$watch('pageState.activePage',angular.bind(this,function(a){b.go(a)}))}}};tripbuddy.core.page.PageDirective.$inject=['pageState','$state'];tripbuddy.components.event.EventDataService=function(a,b){this.list=function(){var c=a.defer();b(function(){c.resolve(SAMPLE_DATA)});return c.promise};this.activePage='events'};tripbuddy.components.event.EventDataService.$inject=['$q','$timeout'];
SAMPLE_DATA=[{id:1,event_type:'driving',start_location:{name:'Home',address:'27229 NE 145th S., Duvall WA 98019',url:'http://goo.gl/maps/WJ6c0'},end_location:{name:'Kalispell',address:'350 N Main St Kalispell, MT, 59901',url:'http://goo.gl/maps/UYpl0'},url:'http://goo.gl/maps/cHsYd',date:new Date(2014,6,18),distance:525,hours:9},{id:2,event_type:'hotel',location:{name:'Travelodge Kalispell',address:'350 N Main St Kalispell, MT, 59901',url:'http://www.hotels.com/hotel/details.html?pa=7&pn=1&ps=7&tab=description&destinationId=1435619&searchDestination=Kalispell&hotelId=255442&arrivalDate=07-18-14&departureDate=07-19-14&children[0]=2&rooms[0].childrenAges[0]=7&rooms[0].childrenAges[1]=14&rooms[0].numberOfAdults=2&roomno=1&validate=false&previousDateful=false&reviewOrder=date_newest_first'},
date:new Date(2014,6,18),nightly_price:150,nights:1},{id:3,event_type:'driving',start_location:{name:'Kalispell',address:'350 N Main St Kalispell, MT, 59901',url:'http://goo.gl/maps/UYpl0'},end_location:{name:'Glacier National Park',address:'Highway 8, Swiftcurrent Lake, Glacier National Park, MT 59434',url:'http://goo.gl/maps/L6w2J'},url:'http://goo.gl/maps/7sSEY',date:new Date(2014,6,19),distance:525,hours:4},{id:3,event_type:'hotel',location:{name:'Many Glacier Hotel',address:'Highway 8, Swiftcurrent Lake, Glacier National Park, MT 59434',
url:'https://www.nationalparkreservations.com/lodge/glacier-many-glacier-hotel'},date:new Date(2014,6,19),nightly_price:250,nights:2},{id:3,event_type:'driving',start_location:{name:'Many Glacier Hotel',address:'Highway 8, Swiftcurrent Lake, Glacier National Park, MT 59434',url:'https://www.nationalparkreservations.com/lodge/glacier-many-glacier-hotel'},end_location:{name:'Sheridan',address:'',url:''},url:'http://goo.gl/maps/g6pMH',date:new Date(2014,6,21),distance:525,hours:8},{id:3,event_type:'hotel',
location:{name:'A Sheridan Hotel',address:'',url:''},date:new Date(2014,6,21),nightly_price:250,nights:1},{id:3,event_type:'driving',start_location:{name:'Sheridan',address:'',url:''},end_location:{name:'Rapid City',address:'',url:''},url:'http://goo.gl/maps/7GGI9',date:new Date(2014,6,22),distance:250,hours:3.5},{id:3,event_type:'hotel',location:{name:'A Rapid City Hotel',address:'',url:''},date:new Date(2014,6,22),nightly_price:200,nights:3},{id:3,event_type:'driving',start_location:{name:'Rapid City',
address:'',url:''},end_location:{name:'St. Paul',address:'',url:''},url:'http://goo.gl/maps/7GGI9',date:new Date(2014,6,25),distance:600,hours:8.5}];tripbuddy.components.location.LocationDataService=function(a){this.http_=a;this.locations=[];this.gridOptions={data:'data',enableRowSelection:!0,multiSelect:!1,enableCellEdit:!0,columnDefs:[{field:'id',displayName:'ID',enableCellEdit:!1,enableCellSelection:!1},{field:'name',displayName:'Name',enableCellEdit:!0,enableCellSelection:!0},{field:'address.street',displayName:'Street',enableCellEdit:!0,enableCellSelection:!0},{field:'address.city',displayName:'City',enableCellEdit:!0,enableCellSelection:!0},
{field:'address.state',displayName:'State',enableCellEdit:!0,enableCellSelection:!0},{field:'address.zip',displayName:'Zip',enableCellEdit:!0,enableCellSelection:!0},{field:'geopt.lat',displayName:'Latitude',enableCellEdit:!0,enableCellSelection:!0},{field:'geopt.lon',displayName:'Longitude',enableCellEdit:!0,enableCellSelection:!0},{field:'image_url',displayName:'Feature Image URL',enableCellEdit:!0,enableCellSelection:!0},{field:'url',displayName:'Web URL',enableCellEdit:!0,enableCellSelection:!0},
{field:'notes',displayName:'Notes',enableCellEdit:!0,enableCellSelection:!0}],selectedItems:[]}};tripbuddy.components.location.LocationDataService.$inject=['$http'];tripbuddy.components.location.LocationDataService.prototype.list=function(){this.http_({method:'get',url:'/data/location/list',responseType:'json'}).success(angular.bind(this,function(a,b){this.locations.splice(0,this.locations.length);$.merge(this.locations,a)})).error(angular.bind(this,function(a,b){console.log(b);console.log(a)}))};
tripbuddy.components.location.LocationDataService.prototype.save=function(a){console.log(a);a.id?this.update(a):this.create(a)};tripbuddy.components.location.LocationDataService.prototype.create=function(a){this.http_({method:'post',url:'/data/location/create',responseType:'json',data:{location:a}}).success(angular.bind(this,function(b,c){a.id=b.id;this.locations.push(a)})).error(angular.bind(this,function(a,c){console.log(c);console.log(a)}))};
tripbuddy.components.location.LocationDataService.prototype.update=function(a){this.http_({method:'post',url:'/data/location/update',responseType:'json',data:{location:a}}).success(angular.bind(this,function(a,c){console.log(a)})).error(angular.bind(this,function(a,c){console.log(c);console.log(a)}))};
tripbuddy.components.location.LocationDataService.prototype.delete=function(a){this.http_({method:'get',url:'/data/location/delete',responseType:'json',params:{id:a.id}}).success(angular.bind(this,function(b,c){this.locations.splice(this.locations.indexOf(a),1);console.log(b)})).error(angular.bind(this,function(a,c){console.log(c);console.log(a)}))};tripbuddy.app=angular.module('tripbuddy',['ui.router','ui.bootstrap','ngGrid']);tripbuddy.app.service('pageState',tripbuddy.core.page.PageStateService);tripbuddy.app.service('eventData',tripbuddy.components.event.EventDataService);tripbuddy.app.service('locationData',tripbuddy.components.location.LocationDataService);tripbuddy.app.controller('locationListViewCtrl',tripbuddy.components.location.list.LocationListViewCtrl);tripbuddy.app.directive('page',tripbuddy.core.page.PageDirective);
tripbuddy.app.directive('eventList',tripbuddy.components.event.EventListDirective);tripbuddy.app.config(tripbuddy.components.PageSectionStates);
